import { StyleSheet } from 'react-native';

/** Shared bottom-sheet styles for Pre Check and Post Check modals. */
export function createCheckSheetStyles(colors) {
  return StyleSheet.create({
    postCheckBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.60)',
      justifyContent: 'flex-end',
    },
    postCheckSheet: {
      backgroundColor: colors.background,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingTop: 12,
      maxHeight: '92%',
      borderTopWidth: 1,
      borderColor: colors.border,
      overflow: 'hidden',
    },
    postCheckHandle: {
      width: 44,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.border,
      alignSelf: 'center',
      marginBottom: 18,
    },
    postCheckTitle: {
      fontSize: 20,
      fontWeight: '800',
      color: colors.text,
      marginBottom: 2,
    },
    postCheckSubtitle: {
      fontSize: 13,
      color: colors.textSecondary,
      marginBottom: 4,
    },
    postCheckSectionLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.9,
      marginBottom: 8,
      marginTop: 18,
    },
    postCheckRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 13,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    postCheckRowLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
      flex: 1,
      marginRight: 8,
    },
    postCheckRowValue: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.primary,
      flexShrink: 1,
    },
    postCheckTotalRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderRadius: 14,
      paddingHorizontal: 16,
      paddingVertical: 16,
      marginTop: 4,
      marginBottom: 8,
      backgroundColor: colors.primarySurface,
      borderWidth: 1.5,
      borderColor: colors.primary + '55',
    },
    postCheckTotalLabel: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.text,
    },
    postCheckTotalValue: {
      fontSize: 18,
      fontWeight: '900',
      color: colors.primary,
    },
    postCheckEditWrap: {
      borderWidth: 1,
      borderRadius: 8,
      paddingHorizontal: 10,
      paddingVertical: 4,
      minWidth: 110,
      alignItems: 'flex-end',
    },
    postCheckEditInput: {
      fontSize: 15,
      fontWeight: '700',
      textAlign: 'right',
      minWidth: 90,
      padding: 0,
    },
    postCheckDropLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.9,
      marginTop: 18,
      marginBottom: 10,
    },
    postCheckDropRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 20,
    },
    postCheckDropOption: {
      flex: 1,
      borderRadius: 14,
      paddingVertical: 14,
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      gap: 5,
    },
    postCheckDropOptionActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primarySurface,
    },
    postCheckDropOptionText: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.textSecondary,
    },
    postCheckDropOptionTextActive: {
      color: colors.primary,
    },
    postCheckHandedOverField: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 14,
      marginBottom: 4,
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.surface,
    },
    postCheckHandedOverText: {
      flex: 1,
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
    },
    postCheckHandedOverMenuOverlay: {
      flex: 1,
      backgroundColor: 'rgba(15, 23, 42, 0.45)',
      justifyContent: 'center',
      paddingHorizontal: 28,
    },
    postCheckHandedOverMenu: {
      borderRadius: 16,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.18,
      shadowRadius: 20,
      elevation: 10,
    },
    postCheckHandedOverMenuRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 16,
      paddingHorizontal: 18,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    postCheckHandedOverMenuRowActive: {
      backgroundColor: (colors.primary ?? '#6366f1') + '12',
    },
    postCheckHandedOverMenuRowText: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.text,
    },
    postCheckHandedOverMenuRowTextActive: {
      color: colors.primary,
      fontWeight: '800',
    },
    postCheckSubmitBtn: {
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 8,
      backgroundColor: colors.primary,
      marginTop: 4,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 6,
    },
    postCheckSubmitBtnDisabled: {
      backgroundColor: colors.border,
      shadowOpacity: 0,
      elevation: 0,
    },
    postCheckSubmitBtnText: {
      fontSize: 16,
      fontWeight: '800',
      color: '#fff',
      letterSpacing: 0.3,
    },
    postCheckPendingWarning: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.warning + '18',
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 4,
      borderWidth: 1,
      borderColor: colors.warning + '55',
    },
    postCheckPendingWarningText: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.warning,
      flex: 1,
    },
    postCheckDivider: {
      height: 1,
      backgroundColor: colors.border,
      marginVertical: 10,
    },
    preCheckSummarySheet: {
      width: '100%',
      maxHeight: '88%',
      flexDirection: 'column',
    },
    postCheckHandoverSheet: {
      width: '100%',
      flexDirection: 'column',
      flexShrink: 0,
    },
    preCheckSummaryScrollContent: {
      paddingBottom: 20,
      paddingHorizontal: 20,
    },
    preCheckStockCard: {
      backgroundColor: colors.surface,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: colors.border,
    },
    preCheckStockCardTitle: {
      flex: 1,
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
    },
    preCheckStockCardMeta: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.textSecondary,
      marginTop: 8,
    },
    preCheckStockStatusOk: {
      fontSize: 11,
      fontWeight: '700',
      color: '#16a34a',
      marginTop: 6,
    },
    preCheckStockStatusShort: {
      fontSize: 11,
      fontWeight: '700',
      color: '#dc2626',
      marginTop: 6,
    },
    preCheckShortfallBanner: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      backgroundColor: colors.warning + '18',
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: colors.warning + '55',
    },
    preCheckShortfallBannerText: {
      flex: 1,
      fontSize: 12,
      fontWeight: '600',
      color: colors.warning ?? '#f59e0b',
      lineHeight: 18,
    },
    preCheckSyncBanner: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      backgroundColor: (colors.primary ?? '#6366f1') + '14',
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: (colors.primary ?? '#6366f1') + '44',
    },
    preCheckSyncBannerText: {
      flex: 1,
      fontSize: 12,
      fontWeight: '600',
      color: colors.primary ?? '#6366f1',
      lineHeight: 18,
    },
    sheetFooter: {
      paddingHorizontal: 20,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      backgroundColor: colors.background,
    },
  });
}
