import { StyleSheet } from 'react-native';
import { spacing, borderRadius } from '../../constants/theme';

export function createDashboardModalStyles(colors) {
  return StyleSheet.create({
    modalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      padding: spacing.lg,
    },
    modalCard: {
      backgroundColor: colors.surface,
      borderRadius: borderRadius.lg,
      padding: spacing.lg,
      maxHeight: '85%',
    },
    modalTitle: { fontSize: 18, fontWeight: '800', color: colors.text, marginBottom: spacing.sm },
    modalSubtitle: { fontSize: 13, color: colors.textSecondary, marginBottom: spacing.md },
    modalCloseBtn: {
      marginTop: spacing.lg,
      paddingVertical: 14,
      borderRadius: borderRadius.md,
      backgroundColor: colors.primary,
      alignItems: 'center',
    },
    modalCloseBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },
    routePickRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 14,
      paddingHorizontal: spacing.sm,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    routePickRowActive: { backgroundColor: colors.primary + '12' },
    routePickName: { fontSize: 16, fontWeight: '600', color: colors.text, flex: 1 },
    profileHero: { alignItems: 'center', marginBottom: spacing.md },
    profileAvatarLg: {
      width: 96,
      height: 96,
      borderRadius: 48,
      borderWidth: 3,
      borderColor: colors.primary + '55',
      overflow: 'hidden',
      backgroundColor: colors.background,
    },
    profileNameLg: {
      fontSize: 20,
      fontWeight: '800',
      color: colors.text,
      marginTop: spacing.md,
      textAlign: 'center',
    },
    profileRole: { fontSize: 13, fontWeight: '700', color: colors.primary, marginTop: 4 },
    profilePhoneRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginTop: spacing.md,
      padding: spacing.md,
      backgroundColor: colors.background,
      borderRadius: borderRadius.md,
      borderWidth: 1,
      borderColor: colors.border,
    },
    profilePhoneText: { flex: 1, fontSize: 16, fontWeight: '600', color: colors.text },
    profileNoPhone: {
      fontSize: 14,
      color: colors.textSecondary,
      fontStyle: 'italic',
      marginTop: spacing.sm,
    },
    syncSuccessAccent: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: colors.primary + '18',
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
      marginBottom: spacing.md,
    },
    syncSuccessTitle: {
      fontSize: 20,
      fontWeight: '800',
      color: colors.text,
      textAlign: 'center',
      marginBottom: spacing.sm,
    },
    syncSuccessSubtitle: {
      fontSize: 14,
      lineHeight: 21,
      color: colors.textSecondary,
      textAlign: 'center',
      marginBottom: spacing.lg,
    },
    commissionModalRangeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 12,
      paddingHorizontal: 4,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    commissionModalRangeLabel: { fontSize: 12, fontWeight: '600', color: colors.textSecondary },
    commissionModalRangeValue: { fontSize: 15, fontWeight: '700', color: colors.primary },
    commissionModalActionRow: { flexDirection: 'row', gap: 10, marginTop: spacing.sm },
    commissionModalCancelBtn: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 12,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
    },
    commissionModalCancelText: { fontSize: 16, fontWeight: '700', color: colors.text },
    commissionModalApplyBtn: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 12,
      backgroundColor: colors.primary,
      alignItems: 'center',
    },
    commissionModalApplyText: { fontSize: 16, fontWeight: '700', color: '#fff' },
    commissionModalDoneBtn: { alignSelf: 'flex-end', padding: 8 },
    commissionModalDoneText: { fontWeight: '600' },
    initialSyncCenter: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: spacing.lg,
    },
    initialSyncTitle: {
      marginTop: spacing.lg,
      fontSize: 17,
      fontWeight: '700',
      textAlign: 'center',
    },
    initialSyncSub: {
      marginTop: spacing.sm,
      fontSize: 14,
      textAlign: 'center',
    },
  });
}
